# fly.toml file generated for empty-butterfly-7978 on 2023-04-14T10:45:36+01:00

app = "empty-butterfly-7978"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[build.args]
  GIT_REPO_URL="https://github.com/ndchorley/chess-games.git"

[env]
  PORT="8080"
  GAMES_DIRECTORY="/games"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

